### PR TITLE
Dump the entire event including the 'Event' container element

### PR DESCRIPTION
**Pull request by iglocska**
This will allow get.py to create a JSON object that can be digested by up.py

### CODE REVIEW

**Comment by adulau** [comment]
Thank you for the contribution. Sometime It can be just small details ;-)

**Comment by iglocska** [comment]
Was an odd issue for sure and the error reporting from MISP definitely
isn't clear enough

**Comment by Rafiot** [comment]
I was thinking this code was reproducing the error I had in the viper module, and it wasn't (sending the event ID as unicode instead of int produce the same error message :) )

But thank you for the fix anyway :)

**Comment by adulau** [comment]
By the way, I just fixed another bug https://github.com/CIRCL/PyMISP/commit/c456538528e0545d5676536ba4e00fb762ac0604 for the event_id as these are integers. It doesn't make sense to lstrip these ;-) Tested on prod.

**Pull request merged**
