### PR TITLE
support org_id & orgc_id

### PR DESCRIPTION
**Pull request by garanews**

### CODE REVIEW

**Comment by Rafiot** [comment]
Squash-merged here: 
https://github.com/CIRCL/PyMISP/commit/6885779be5424e78976aa40b10aa785df37f0461

**Comment by garanews** [comment]
Hello,
I have no errors sending the new fields but at MISP side the json is still arriving with defaults fields:

 --- sender side ---
from pymisp import PyMISP
from datetime import datetime
misp = PyMISP('http://1.2.3.4' ,'fkjdsfkjs93erjijfdk', False, 'json')
event = misp.new_event(1, 1, 1, "test", date=datetime.now().strftime('%Y-%m-%d'), published=True, **org_id="2", orgc_id="3"**)


--- receiver side ---

/var/www/MISP/app/tmp/logs/[974]: 2016-11-16 10:26:58 Notice: Event (27) added by User "admin@myorg.com" (1). -- published () => (1), distribution () => (1), proposal_email_lock () => (0), locked () => (0), publish_timestamp () => (0), info () => (test), **orgc_id () => (2), org_id () => (2)**, analysis () => (1), date () => (2016-11-16), threat_level_id () => (1), user_id () => (1), uuid () => (1111-badc-411-8f87-03ddddd02)
/var/www/MISP/app/tmp/logs/[974]: 2016-11-16 10:26:58 Notice: Event (27) updated by User "admin@myorg.com" (1). -- publish_timestamp (0) => (1479292018)

**Comment by Rafiot** [comment]
@iglocska is it expected?

**Comment by iglocska** [comment]
Looks correct, basically MISP prevents you from spoofing a different organisation as the creator. Sync users are exempt from this.

**Comment by garanews** [comment]
iglocska commented 14 days ago
Basically:

orgc_id: the organisation that has created the event
org_id: the local owner of the event

So if for example org A creates an event on misp a and org B that has access to misp a pulls the event to their home instance misp b, the event will become orgc = org A, org = org B


so objective is that orgB wants to publish some event into MISP owned by orgA without publishing as orgA but as orgB

hope you understand...

**Comment by iglocska** [comment]
Not entirely sure I understand. Basically the behaviour is as follows:

If a user pushes an event to MISP, MISP will only retain the pushed orgc_id if the user is allowed to create events for other organisations (this requires the perm_sync permission). If the user doesn't have this permission, MISP prevents the user from impersonating a 3rd party and reverts to the user's own organisation.

So if I as user of org B want to create an event on misp a, I can only create events as orgc = org B. If I have sync user access, I get the privilege to sync events of other organisations and I can create events for other orgs.

**Comment by garanews** [comment]
so the next question would be: is it possible through api to send an event into misp of orgA as an user X that belongs to the orgB?
so api needs to accept in input not just the api key but also the user.
so in your opinion at sender side I will need, api key, url, org B and user X?

**Comment by garanews** [comment]
another thing: now through the api I'm not sending the user and it seems the system choose for me ( added by User "admin@myorg.com" (1) )
So I'm sending as user admin with admin roles and have no rights to add events into local organization B that the user admin created previously?

**Pull request closed without merging**
